### ISSUE TITLE
Add searching for required files from start-up directory

### ISSUE THREAD

**Issue by nickshanks347** [codefenix-ConChaos/NewsDesk#1]
The script should automatically get the start-up directory from Synchronet. 

I didn't want the files in my `/sbbs/mods` folder so I created the folder `/sbbs/mods/newsdesk` folder yet the script still looks in `/sbbs/mods`. I manually edited the script to include `newsdesk` in the path but it'd be nice if it did it automatically :)

I think you can use something like [this](https://gitlab.synchro.net/main/sbbs/-/blob/master/xtrn/DDAreaChoosers/DDMsgAreaChooser.js#L141)

**Comment by codefenix-ConChaos** [comment]
Changing all occurrences of `system.mods_dir` to `js.exec_dir` should have the desired effect, so that it uses the path where news.js is located rather than the /sbbs/mods path.

This may change the way news.js gets called from logon.js though. Will have to do more testing.

**Comment by codefenix-ConChaos** [comment]
Updated news.js. It should now find the settings file and header & graphics files as long as they're in the same directory as news.js.

If you're calling news.js from your logon.js script, call it with `bbs.exec("?../path_to/news.js");`.
